spring:
  application:
    name: lab-admin-service

  datasource:
    url: jdbc:postgresql://localhost:5433/labdb
    username: labuser
    password: labpassword

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true